spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/events_api?useSSL=false&serverTimezone=UTC
    username: developer
    password: junior087
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect